### PR TITLE
Add soft-delete filter on Deployments finds

### PR DESCRIPTION
**Pull request by mjlescano**
Test pending.

Before accepting and Deploying this branch we have to set { delete: false } on existing Deployments.

### CODE REVIEW

**Comment by mjlescano** [comment]
Hand in hand with https://github.com/DemocracyOS/manager/pull/33

**Comment by gvilarino** [comment]
I don't quite understand why we're using a boolean value for that instead of a `Date` or a status value instead, like the previous approach.

**Comment by mjlescano** [comment]
We can't use only `Date` because we should create an index when `deletedAt = undefined`, and that's impossible. It can only be done with existent keys: http://docs.mongodb.org/manual/core/index-sparse/.

**Comment by mjlescano** [comment]
Closing because deprecated.

**Pull request closed without merging**
